name: Node.js CI

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Alto Push
    runs-on: ubuntu-latest

    steps:
      - name: Set node version
        uses: node16
      - name: Install Altostra CLI
        run: |
             npm install -g @altostra/cli
             alto --version
             alto api-key set ${{ secrets.ALTO_API_KEY }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Push to Altostra
        run: alto push v$(node -p -e "require('./package.json').version") --json
